title: Marisa G. Rodríguez
description: Biosystems Engineering major at Auburn University 
<a href="MGR_resume_sp2020.pdf">Resume</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky
